// Code generated by encore. DO NOT EDIT.

package admin

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// Endpoints annotated with `auth` are public and requires authentication
	// Learn more: encore.dev/docs/primitives/services-and-apis#access-controls
	GetAdminDashboardData(ctx context.Context) (*DashboardData, error)
}
